export enum Section {
  Profile = "Profiles",
  Market = "Markets",
  Social = "Socials",
  Tool = "Tools",
}

export enum Icon {
  XWatch = "0xwatch.svg",
  OneInch = "1inch.svg",
  Blur = "blur.svg",
  CoinGecko = "coingecko.svg",
  CryptoPunks = "cryptopunks.png",
  Curve = "curve.svg",
  Debank = "debank.svg",
  Discord = "discord.svg",
  Eigenphi = "eigenphi.svg",
  Etherscan = "etherscan.svg",
  Facebook = "facebook.svg",
  FlipsWatch = "flipswatch.svg",
  Gem = "gem.svg",
  Genie = "genie.svg",
  GitHub = "github.svg",
  Instagram = "instagram.svg",
  LooksRare = "looksrare.svg",
  Medium = "medium.svg",
  Meebits = "meebits.svg",
  Mirror = "mirror.svg",
  NFTScan = "nftscan.svg",
  NFTinit = "nftinit.png",
  NFTEye = "nfteye.svg",
  OpenSea = "opensea.svg",
  Rainbow = "rainbow.png",
  Rarible = "rarible.svg",
  Reddit = "reddit.svg",
  Sudoswap = "sudoswap.svg",
  SushiSwap = "sushiswap.svg",
  Telegram = "telegram.svg",
  TraitSniper = "traitsniper.svg",
  Twitter = "twitter.svg",
  Uniswap = "uniswap.svg",
  Unknown = "unknown.svg",
  Vscode = "vscode.svg",
  Website = "website.svg",
  X2Y2 = "x2y2.svg",
}
