export enum Section {
  Profile = "Profiles",
  Market = "Markets",
  Social = "Socials",
  Other = "Others",
}

export enum Icon {
  OneInch = "1inch.svg",
  CoinGecko = "coingecko.svg",
  Curve = "curve.svg",
  Debank = "debank.svg",
  Discord = "discord.svg",
  Etherscan = "etherscan.svg",
  Facebook = "facebook.svg",
  Gem = "gem.svg",
  Genie = "genie.svg",
  GitHub = "github.svg",
  Instagram = "instagram.svg",
  LarvaLabs = "larvalabs.svg",
  LooksRare = "looksrare.svg",
  Medium = "medium.svg",
  Mirror = "mirror.svg",
  NFTEye = "nfteye.svg",
  OpenSea = "opensea.svg",
  Rainbow = "rainbow.png",
  Rarible = "rarible.svg",
  Reddit = "reddit.svg",
  SushiSwap = "sushiswap.svg",
  Telegram = "telegram.svg",
  TraitSniper = "traitsniper.svg",
  Twitter = "twitter.svg",
  Uniswap = "uniswap.svg",
  Unknown = "unknown.svg",
  Vscode = "vscode.svg",
  Website = "website.svg",
  X2Y2 = "x2y2.svg",
}
